dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8 

env: C_COMPILER=gcc-8
env: CXX_COMPILER=g++-8

script:
  - cmake .
  - cmake --build .
